config/routes.rb
Rails.application.routes.draw do
  root "home#home"

  get 'home' => 'home#home'
  get 'about' => 'home#about'
  get 'photos' => 'home#photos'
  get 'registry' => 'home#registry'
  get 'contact' => 'home#contact'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :file,
    styles: {
      thumbnail: "128x128"
    },
    :url => "/system/:class/:attachment/:basename/:style/:basename.:extension",
  	:path => ":rails_root/public/system/:class/:attachment/:basename/:style/:basename.:extension"

  validates_attachment :file, :presence => true, :size => { :in => 0..20.megabytes }
  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  EMAIL_REGEX=/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  validates_presence_of :name
  validates :name, length:{minimum: 3}

  validates_presence_of :email
  validates :email, length:{minimum: 3}
  validates_format_of :email, :with=>EMAIL_REGEX, :on=>:create
  validates_format_of :email, :with=>EMAIL_REGEX, :on=>:update

  validates_presence_of :entree

  validates_inclusion_of :shuttle, :in => [true, false]
  
  def self.shuttles
    Rsvp.where(shuttle:true)
  end

  def self.entrees
    results = {}
    Rsvp.all.each do |a|
      if(results[a.entree] == nil)
        results[a.entree] = [a]
      else
        results[a.entree].push(a)
      end
    end
    results
  end

  def to_s
    "#{id} | #{name} | #{email} | #{entree} | #{shuttle}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :set_constants

  def set_constants
    @app_title='Melanie+Michael'
    @asset_root=''
    @email='wedding@melanieandmichael.us'
    @crate_registry_url='http://www.crateandbarrel.com/Gift-Registry/Michael-Lin-and-Melanie-So/r5198518'
    @amazon_registry_url='http://www.amazon.com/registry/wedding/Z9LEWSYZSJND'
    @honeyfund_url = 'http://www.honeyfund.com/wedding/melanieandmichael'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
  
  def about
  end
  
  def info
  end

  def photos
    @ceremony_images = Photo.where(category: :ceremony).order(:file_file_name)
    @reception_images = Photo.where(category: :reception).order(:file_file_name)
    @outtake_images = Photo.where(category: :outtake).order(:file_file_name)
  end

  def registry
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_tab_selected?(page_name)
    "selected" if params[:action] == page_name
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
#about
  .section
    %h1
      MELANIE+MICHAEL
    %p
      Once upon a time dinosaurs roamed the earth.  They walked around and did normal dinosaur stuff until one day 66 million years ago an astroid crashed into the Yucatan Peninsula and obliterated the vast majority of terrestrial life on Earth.  Mammals rose to fill the void, and they too walked around and did  normal mammal stuff for a few more million years, which consisted mostly of digging around in the dirt and eating bugs.  Eventually they invented the airplane.
      %br
      %br
      ="Nothing of much consequence happened after that until "
      %span.purple
        June 6, 2002
      ="when Melanie and Michael met, dated, and fell in love.  So mass extinctions can cause good things too, it just takes time."
  .section.clearfix{:style=>"margin: 0px 0px 40px 0px;"}
    .left{:style=>"width:50%;"}
      %div
        %h1
          MELANIE ALLISON SO
        %p{:style=>"padding:0px 2px 0px 0px;"}
          %span.purple
            Melanie 
          loves Pixar, cockatiels, Gund bears, baking, chocolate, and baking things with chocolate.  She is a second degree black belt in Yongmudo and Michael once saw her break four bricks with a palm strike.
          %br
          %br
          She currently works as a Revenue Manager at Counsyl.  She thinks Michael is disobedient and infuriating and sassy and she loves every moment spent with him.
    .right{:style=>"width:50%;"}
      %div
        %h1
          MICHAEL HUAITZER LIN
        %p{:style=>"padding:0px 0px 0px 10px;"}
          %span.purple
            Michael 
          loves Legos, owls, food, archery, and running and can usually be found doing some combination of those things.  He is slightly taller than Melanie and wishes he was best friends with David Attenborough.
          %br
          %br
          He currently works as an engineer at Amino.  He thinks Melanie is the kindest and most beautiful person you will ever meet.

  .section
    .gallery.clearfix    
      =image_tag("#{@asset_root}/images/gallery/088.jpg", :class => "split")
      =image_tag("#{@asset_root}/images/gallery/179.jpg", :class => "split")

      =image_tag("#{@asset_root}/images/gallery/113.jpg", :class => "split")
      =image_tag("#{@asset_root}/images/gallery/176.jpg", :class => "split")

      =image_tag("#{@asset_root}/images/gallery/116.jpg", :class => "split")
      =image_tag("#{@asset_root}/images/gallery/064.jpg", :class => "split")

      =image_tag("#{@asset_root}/images/gallery/122.jpg", :style => "width:764px; height:508px")

      =image_tag("#{@asset_root}/images/gallery/085.jpg", :class => "split")
      =image_tag("#{@asset_root}/images/gallery/083.jpg", :class => "split")
  
      =image_tag("#{@asset_root}/images/gallery/171.jpg", :class => "split")
      =image_tag("#{@asset_root}/images/gallery/269.jpg", :class => "split")
  
      =image_tag("#{@asset_root}/images/gallery/146.jpg", :class => "split")
      =image_tag("#{@asset_root}/images/gallery/058.jpg", :class => "split")
  
      =image_tag("#{@asset_root}/images/gallery/102.jpg", :style => "width:764px; height:508px")

      =image_tag("#{@asset_root}/images/gallery/018.jpg", :class => "split")
      =image_tag("#{@asset_root}/images/gallery/063.jpg", :class => "split")

      =image_tag("#{@asset_root}/images/gallery/177.jpg", :class => "split")
      =image_tag("#{@asset_root}/images/gallery/181.jpg", :class => "split")

      =image_tag("#{@asset_root}/images/gallery/082.jpg", :class => "split")
      =image_tag("#{@asset_root}/images/gallery/182.jpg", :class => "split")

      =image_tag("#{@asset_root}/images/gallery/034.jpg", :style => "width:764px; height:508px")

      =image_tag("#{@asset_root}/images/gallery/247.jpg", :class => "split")
      =image_tag("#{@asset_root}/images/gallery/054.jpg", :class => "split")

      =image_tag("#{@asset_root}/images/gallery/107.jpg", :class => "split")
      =image_tag("#{@asset_root}/images/gallery/169.jpg", :class => "split")

      =image_tag("#{@asset_root}/images/gallery/120.jpg", :style => "width:100%")
      =image_tag("#{@asset_root}/images/gallery/192.jpg", :style => "width:764px; height:508px")

app/views/home/contact.html.haml
#contact
  %h1
    CONTACT
  %p
    If you have any questions or well-wishes, please email us at  
    =mail_to(@email, @email, :class=>'purple')

app/views/home/home.html.haml
#home
  =image_tag("#{@asset_root}/images/treehouse.jpg", :style=>"margin:40px 0px 0px 0px;")

app/views/home/info.html.haml
#info
  .section
    %h1
      WHEN
    %p
      %span.title
        September 6, 2014
      %br
      Guest should arrive by half past four in the afternoon 
      %span.purple
        4:30 PM 
      for the ceremony
      %br
      %br
      Dinner and dancing to follow
      %br
  .section
    %h1
      WHERE
    %p
      =link_to('Cinnabar Hills Golf Club', 'http://www.cinnabarhills.com/', :class=>'title')
      %br
      23600 McKean Road
      %br
      San Jose, CA 95141
      %br
      %br
      %iframe{ :src=>"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3179.2987335862545!2d-121.751488!3d37.169370999999956!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808e25b33f5a6939%3A0x1278219d99934af2!2sCinnabar+Hills+Golf+Club!5e0!3m2!1sen!2sus!4v1401086999507", :width=>"768", :height=>"580", :frameborder=>"0", :style=>"border:0"}
  .section
    %h1
      TRANSPORTATION
    %p
      We have chartered a shuttle which you are welcome to use.  Shuttles will depart from the 
      %span.purple
        Hyatt Regency Santa Clara
      at
      %span.purple
        4:00PM
      and will return from Cinnabar Hills at 
      %span.purple
        10:45PM.  
      You will be responsible for finding your way home from the shuttle drop off point, so please remember to 
      %span.purple
        drive safely
  .section
    %h1
      WHAT TO WEAR
    %p
      Formal and semi-formal mean different things to different people, but the groomsmen will be wearing 
      %span.purple
        suits and ties 
      and the bridesmaids will be wearing 
      %span.purple
        cocktail dresses.  
      Please wear whatever will make you feel comfortable given those parameters.  Please keep in mind that the ceremony will be outdoors in the lovely (and hot) California sun, but the reception will be indoors with the pleasant (and powerful) air conditioning. Please wear whatever shoes make you comfortable
  .section
    %h1
      DINNER
    %p
      Once your invitation arrives you will be able to choose from several entrees.  Please let us know if you have any dietary restrictions and we will do our best to accomodate
      %div.clearfix
        .inline.left{:style=>"width:32%;"}
          %p
            %span.purple
              Rib-Eye Steak
            %br
            Rib-eye steak seared and served with red wine butter
        .inline{:style=>"width:32%;"}
          %p
            %span.purple
              Italian Stuffed Chicken
            %br
            Baked chicken breast stuffed with prosciutto, boursin, spinach, and sun-dried tomatoes served with a roasted garlic tomato cream sauce
        .inline.right{:style=>"width:32%;"}
          %p
            %span.purple
              Vegetable Risotto
            %br
            Risotto with mushrooms, tomatoes, spinach, garlic and parmesan cheese
      %p
        %span.purple
          Cake 
        will also be served because it is delicious.
  .section
    %h1
      ACCOMMODATIONS
    %p
      =link_to('Hyatt Regency Santa Clara', 'http://www.santaclara.hyatt.com/en/hotel/home.html', :class=>'title')
      %br
      5101 Great America Parkway
      %br
      Santa Clara, California, USA, 95054
      %br
      %p
        The hotel is offering 
        =link_to("$102 per night", "http://www.santaclara.hyatt.com/en/hotel/home.html", :class=>"purple")
        if you prepay and agree to their no-cancellation policy, and 
        =link_to("Priceline is offering $103 per night.", "http://www.priceline.com/hotel/hotelOverviewGuide.do?propID=42673&refid=TMTRANSACT&sendId=17153582604&email_subject_line=Cheng-Yu%20Lee%20Trip%20to%20Santa%20Clara,%20CA%20on%20September%205,%202014&batchId=274806&refclickid=20140624%7C5%7COFFER%7CEMAIL_ITINERARY_INT%7CHOTEL_NAME&ea=47B74C833C5B7A20408A93E042570E37F1255085D23A20AF&utm_medium=email&utm_source=TM_HOTEL_EMAIL_ITINERARY_INT&utm_campaign=TM_HOTEL_EMAIL_ITINERARY_INT_17153582604", :class=>"purple")
        We also have an additional nine rooms blocked at $119 per night in case hotel prices increase or the hotel reaches full capacity. Please contact us to switch the hotel reservation to your name.
      %br
      %iframe{ :src=>"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3169.3517101245866!2d-121.97659200000001!3d37.405161!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fc9c671bf5d63%3A0x41143de25661b172!2sHyatt+Regency+Santa+Clara!5e0!3m2!1sen!2sus!4v1405915084142", :width=>"768", :height=>"580", :frameborder=>"0", :style=>"border:0"}

app/views/home/photos.html.haml
#photos
  .section
    %h1
      PHOTOBOOTH
    %p
      %span.title
        Wild About You Photography
      %br
      Special thanks to Chris and Lily from Wild About Your Photography for photographing our special day.  Photos from the photobooth are at:
      %br
      %br
      =link_to('Wildbooth Photos', 'http://gallery.wildaboutyouphotography.com/guestlogin/melanieandmikeswildbooth/', :class=>'purple')
      %br
      Password: MMTugs
  .section
    %h1
      CEREMONY
    %p.gallery
      =render_gallery_for @ceremony_images, list_tag: :div, item_tag: :span, item_class: :thumbnail

  .section
    %h1
      RECEPTION
    %p.gallery
      =render_gallery_for @reception_images, list_tag: :div, item_tag: :span, item_class: :thumbnail

  .section
    %h1
      OUTTAKES
    %p.gallery
      =render_gallery_for @outtake_images, list_tag: :div, item_tag: :span, item_class: :thumbnail

app/views/home/registry.html.haml
#registry
  %h1
    REGISTRY
  %p
    We have created registries 
    at the following online retailers.
    %br
    %br
    Thank you for your generous gift!  
    %span.purple
      100% of proceeds 
    will be donated to disadvantaged Michaels and Melanies in the Bay Area.  Thank you for helping us begin our new lives together!
    %span.purple
      We are happy to receive gifts after the ceremony,
      so please don't worry about rush delivery
  .section.center
    =link_to image_tag("#{@asset_root}/images/registry/amazon.jpg"), @amazon_registry_url
    =link_to image_tag("#{@asset_root}/images/registry/honeyfund.jpg"), @honeyfund_url
    =link_to image_tag("#{@asset_root}/images/registry/crate.jpg"), @crate_registry_url

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title
      =@app_title
    =stylesheet_link_tag    "application", media:"all", "data-turbolinks-track"=>true
    =javascript_include_tag "application", "data-turbolinks-track"=>true
    =csrf_meta_tags
  %body
    #header
      =link_to('HOME', home_url, :class=>is_tab_selected?('home'))
      .inline.spacer
      =link_to('MELANIE+MICHAEL', about_url, :class=>is_tab_selected?('about'))
      .inline.spacer
      =link_to('PHOTOS', photos_url, :class=>is_tab_selected?('photos'))
      .inline.spacer
      =link_to('REGISTRY', registry_url, :class=>is_tab_selected?('registry'))
      .inline.spacer
      =link_to('CONTACT', contact_url, :class=>is_tab_selected?('contact')) 
    #scene
      =yield